### ISSUE TITLE
Chrome does not work on OS X 10.11 El Capitan.

### ISSUE THREAD

**Issue by ariporad** [Nikola-K/RESTool#15]
Hi Everyone!
Awesome app, but I can't seem to use chrome with in on OS X El Capitan. Chrome simply does not show up in the list of browsers. (Safari does though).

I'm more than happy to test anything that is needed, for this issue or others.

Thanks!
Ari

**Comment by Nikola-K** [comment]
Hi @ariporad, thanks for letting me know.

Could you go through steps described here https://github.com/Nikola-K/RESTool#how-to-report-issues

And attach application log to the issue?

Also could you try manually locating the RES file and verifying that it exists.

The default file location is documented here:

https://www.reddit.com/r/Enhancement/wiki/backing_up_res_settings#wiki_chrome_-_os_x

**Comment by ariporad** [comment]
@Nikola-K: The logging setting is not persisting between restarts of the app, so I'm not really sure how.

Also, in the Application Support chrome folder, there is no `Default` There's a few `Profile X` files (ex. `Profile 3`, `Profile 9`), but no `Default`s.

**Comment by Nikola-K** [comment]
Okay thanks for the feedback. It has to do with chrome profiles not being really implemented properly. I'll see that I fix it over the next week. It's not OS X specific issue.

You can keep progress of the bug here: https://github.com/Nikola-K/RESTool/issues/16

Once it's resolved I'll wait for you or someone else to confirm that it's working on 'El Capitan' before closing this issue.

Thanks again, I really appreciate the feedback!

**Comment by ariporad** [comment]
No Problem. Happy to help!

**Comment by Nikola-K** [comment]
Added chrome support in the latest release.
